SET DEFINE OFF

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (1, 'bulbasaur', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (2, 'ivysaur', 1);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (3, 'venusaur', 2);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (4, 'charmander', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (5, 'charmeleon', 4);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (6, 'charizard', 5);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (7, 'squirtle', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (8, 'wartortle', 7);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (9, 'blastoise', 8);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (10, 'caterpie', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (11, 'metapod', 10);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (12, 'butterfree', 11);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (13, 'weedle', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (14, 'kakuna', 13);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (15, 'beedrill', 14);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (16, 'pidgey', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (17, 'pidgeotto', 16);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (18, 'pidgeot', 17);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (19, 'rattata', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (20, 'raticate', 19);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (21, 'spearow', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (22, 'fearow', 21);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (23, 'ekans', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (24, 'arbok', 23);


INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (172, 'pichu', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (25, 'pikachu', 172);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (26, 'raichu', 25);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (27, 'sandshrew', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (28, 'sandslash', 27);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (29, 'nidoran-f', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (30, 'nidorina', 29);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (31, 'nidoqueen', 30);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (32, 'nidoran-m', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (33, 'nidorino', 32);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (34, 'nidoking', 33);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (173, 'cleffa', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (35, 'clefairy', 173);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (36, 'clefable', 35);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (37, 'vulpix', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (38, 'ninetales', 37);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (174, 'igglybuff', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (39, 'jigglypuff', 174);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (40, 'wigglytuff', 39);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (41, 'zubat', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (42, 'golbat', 41);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (43, 'oddish', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (44, 'gloom', 43);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (45, 'vileplume', 44);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (46, 'paras', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (47, 'parasect', 46);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (48, 'venonat', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (49, 'venomoth', 48);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (50, 'diglett', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (51, 'dugtrio', 50);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (52, 'meowth', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (53, 'persian', 52);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (54, 'psyduck', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (55, 'golduck', 54);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (56, 'mankey', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (57, 'primeape', 56);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (58, 'growlithe', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (59, 'arcanine', 58);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (60, 'poliwag', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (61, 'poliwhirl', 60);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (62, 'poliwrath', 61);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (63, 'abra', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (64, 'kadabra', 63);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (65, 'alakazam', 64);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (66, 'machop', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (67, 'machoke', 66);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (68, 'machamp', 67);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (69, 'bellsprout', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (70, 'weepinbell', 69);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (71, 'victreebel', 70);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (72, 'tentacool', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (73, 'tentacruel', 72);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (74, 'geodude', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (75, 'graveler', 74);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (76, 'golem', 75);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (77, 'ponyta', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (78, 'rapidash', 77);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (79, 'slowpoke', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (80, 'slowbro', 79);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (81, 'magnemite', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (82, 'magneton', 81);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (83, 'farfetchd', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (84, 'doduo', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (85, 'dodrio', 84);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (86, 'seel', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (87, 'dewgong', 86);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (88, 'grimer', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (89, 'muk', 88);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (90, 'shellder', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (91, 'cloyster', 90);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (92, 'gastly', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (93, 'haunter', 92);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (94, 'gengar', 93);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (95, 'onix', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (96, 'drowzee', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (97, 'hypno', 96);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (98, 'krabby', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (99, 'kingler', 98);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (100, 'voltorb', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (101, 'electrode', 100);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (102, 'exeggcute', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (103, 'exeggutor', 102);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (104, 'cubone', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (105, 'marowak', 104);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (236, 'tyrogue', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (106, 'hitmonlee', 236);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (107, 'hitmonchan', 236);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (108, 'lickitung', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (109, 'koffing', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (110, 'weezing', 109);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (111, 'rhyhorn', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (112, 'rhydon', 111);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (440, 'happiny', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (113, 'chansey', 440);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (114, 'tangela', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (115, 'kangaskhan', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (116, 'horsea', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (117, 'seadra', 116);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (118, 'goldeen', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (119, 'seaking', 118);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (120, 'staryu', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (121, 'starmie', 120);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (439, 'mime-jr', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (122, 'mr-mime', 439);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (123, 'scyther', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (238, 'smoochum', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (124, 'jynx', 238);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (239, 'elekid', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (125, 'electabuzz', 239);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (240, 'magby', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (126, 'magmar', 240);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (127, 'pinsir', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (128, 'tauros', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (129, 'magikarp', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (130, 'gyarados', 129);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (131, 'lapras', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (132, 'ditto', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (133, 'eevee', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (134, 'vaporeon', 133);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (135, 'jolteon', 133);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (136, 'flareon', 133);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (137, 'porygon', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (138, 'omanyte', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (139, 'omastar', 138);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (140, 'kabuto', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (141, 'kabutops', 140);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (142, 'aerodactyl', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (446, 'munchlax', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (143, 'snorlax', 446);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (144, 'articuno', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (145, 'zapdos', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (146, 'moltres', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (147, 'dratini', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (148, 'dragonair', 147);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (149, 'dragonite', 148);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (150, 'mewtwo', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (151, 'mew', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (152, 'chikorita', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (153, 'bayleef', 152);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (154, 'meganium', 153);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (155, 'cyndaquil', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (156, 'quilava', 155);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (157, 'typhlosion', 156);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (158, 'totodile', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (159, 'croconaw', 158);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (160, 'feraligatr', 159);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (161, 'sentret', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (162, 'furret', 161);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (163, 'hoothoot', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (164, 'noctowl', 163);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (165, 'ledyba', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (166, 'ledian', 165);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (167, 'spinarak', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (168, 'ariados', 167);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (169, 'crobat', 42);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (170, 'chinchou', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (171, 'lanturn', 170);


INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (175, 'togepi', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (176, 'togetic', 175);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (177, 'natu', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (178, 'xatu', 177);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (179, 'mareep', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (180, 'flaaffy', 179);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (181, 'ampharos', 180);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (182, 'bellossom', 44);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (298, 'azurill', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (183, 'marill', 298);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (184, 'azumarill', 183);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (438, 'bonsly', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (185, 'sudowoodo', 438);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (186, 'politoed', 61);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (187, 'hoppip', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (188, 'skiploom', 187);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (189, 'jumpluff', 188);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (190, 'aipom', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (191, 'sunkern', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (192, 'sunflora', 191);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (193, 'yanma', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (194, 'wooper', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (195, 'quagsire', 194);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (196, 'espeon', 133);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (197, 'umbreon', 133);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (198, 'murkrow', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (199, 'slowking', 79);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (200, 'misdreavus', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (201, 'unown', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (360, 'wynaut', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (202, 'wobbuffet', 360);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (203, 'girafarig', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (204, 'pineco', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (205, 'forretress', 204);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (206, 'dunsparce', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (207, 'gligar', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (208, 'steelix', 95);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (209, 'snubbull', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (210, 'granbull', 209);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (211, 'qwilfish', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (212, 'scizor', 123);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (213, 'shuckle', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (214, 'heracross', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (215, 'sneasel', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (216, 'teddiursa', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (217, 'ursaring', 216);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (218, 'slugma', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (219, 'magcargo', 218);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (220, 'swinub', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (221, 'piloswine', 220);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (222, 'corsola', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (223, 'remoraid', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (224, 'octillery', 223);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (225, 'delibird', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (458, 'mantyke', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (226, 'mantine', 458);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (227, 'skarmory', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (228, 'houndour', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (229, 'houndoom', 228);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (230, 'kingdra', 117);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (231, 'phanpy', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (232, 'donphan', 231);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (233, 'porygon2', 137);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (234, 'stantler', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (235, 'smeargle', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (237, 'hitmontop', 236);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (241, 'miltank', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (242, 'blissey', 113);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (243, 'raikou', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (244, 'entei', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (245, 'suicune', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (246, 'larvitar', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (247, 'pupitar', 246);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (248, 'tyranitar', 247);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (249, 'lugia', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (250, 'ho-oh', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (251, 'celebi', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (252, 'treecko', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (253, 'grovyle', 252);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (254, 'sceptile', 253);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (255, 'torchic', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (256, 'combusken', 255);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (257, 'blaziken', 256);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (258, 'mudkip', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (259, 'marshtomp', 258);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (260, 'swampert', 259);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (261, 'poochyena', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (262, 'mightyena', 261);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (263, 'zigzagoon', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (264, 'linoone', 263);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (265, 'wurmple', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (266, 'silcoon', 265);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (267, 'beautifly', 266);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (268, 'cascoon', 265);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (269, 'dustox', 268);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (270, 'lotad', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (271, 'lombre', 270);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (272, 'ludicolo', 271);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (273, 'seedot', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (274, 'nuzleaf', 273);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (275, 'shiftry', 274);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (276, 'taillow', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (277, 'swellow', 276);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (278, 'wingull', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (279, 'pelipper', 278);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (280, 'ralts', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (281, 'kirlia', 280);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (282, 'gardevoir', 281);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (283, 'surskit', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (284, 'masquerain', 283);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (285, 'shroomish', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (286, 'breloom', 285);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (287, 'slakoth', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (288, 'vigoroth', 287);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (289, 'slaking', 288);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (290, 'nincada', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (291, 'ninjask', 290);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (292, 'shedinja', 290);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (293, 'whismur', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (294, 'loudred', 293);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (295, 'exploud', 294);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (296, 'makuhita', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (297, 'hariyama', 296);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (299, 'nosepass', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (300, 'skitty', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (301, 'delcatty', 300);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (302, 'sableye', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (303, 'mawile', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (304, 'aron', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (305, 'lairon', 304);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (306, 'aggron', 305);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (307, 'meditite', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (308, 'medicham', 307);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (309, 'electrike', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (310, 'manectric', 309);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (311, 'plusle', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (312, 'minun', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (313, 'volbeat', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (314, 'illumise', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (406, 'budew', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (315, 'roselia', 406);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (316, 'gulpin', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (317, 'swalot', 316);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (318, 'carvanha', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (319, 'sharpedo', 318);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (320, 'wailmer', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (321, 'wailord', 320);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (322, 'numel', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (323, 'camerupt', 322);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (324, 'torkoal', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (325, 'spoink', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (326, 'grumpig', 325);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (327, 'spinda', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (328, 'trapinch', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (329, 'vibrava', 328);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (330, 'flygon', 329);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (331, 'cacnea', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (332, 'cacturne', 331);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (333, 'swablu', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (334, 'altaria', 333);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (335, 'zangoose', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (336, 'seviper', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (337, 'lunatone', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (338, 'solrock', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (339, 'barboach', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (340, 'whiscash', 339);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (341, 'corphish', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (342, 'crawdaunt', 341);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (343, 'baltoy', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (344, 'claydol', 343);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (345, 'lileep', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (346, 'cradily', 345);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (347, 'anorith', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (348, 'armaldo', 347);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (349, 'feebas', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (350, 'milotic', 349);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (351, 'castform', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (352, 'kecleon', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (353, 'shuppet', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (354, 'banette', 353);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (355, 'duskull', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (356, 'dusclops', 355);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (357, 'tropius', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (433, 'chingling', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (358, 'chimecho', 433);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (359, 'absol', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (361, 'snorunt', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (362, 'glalie', 361);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (363, 'spheal', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (364, 'sealeo', 363);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (365, 'walrein', 364);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (366, 'clamperl', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (367, 'huntail', 366);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (368, 'gorebyss', 366);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (369, 'relicanth', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (370, 'luvdisc', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (371, 'bagon', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (372, 'shelgon', 371);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (373, 'salamence', 372);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (374, 'beldum', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (375, 'metang', 374);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (376, 'metagross', 375);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (377, 'regirock', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (378, 'regice', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (379, 'registeel', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (380, 'latias', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (381, 'latios', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (382, 'kyogre', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (383, 'groudon', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (384, 'rayquaza', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (385, 'jirachi', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (386, 'deoxys', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (387, 'turtwig', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (388, 'grotle', 387);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (389, 'torterra', 388);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (390, 'chimchar', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (391, 'monferno', 390);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (392, 'infernape', 391);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (393, 'piplup', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (394, 'prinplup', 393);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (395, 'empoleon', 394);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (396, 'starly', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (397, 'staravia', 396);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (398, 'staraptor', 397);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (399, 'bidoof', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (400, 'bibarel', 399);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (401, 'kricketot', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (402, 'kricketune', 401);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (403, 'shinx', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (404, 'luxio', 403);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (405, 'luxray', 404);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (407, 'roserade', 315);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (408, 'cranidos', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (409, 'rampardos', 408);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (410, 'shieldon', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (411, 'bastiodon', 410);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (412, 'burmy', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (413, 'wormadam', 412);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (414, 'mothim', 412);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (415, 'combee', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (416, 'vespiquen', 415);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (417, 'pachirisu', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (418, 'buizel', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (419, 'floatzel', 418);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (420, 'cherubi', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (421, 'cherrim', 420);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (422, 'shellos', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (423, 'gastrodon', 422);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (424, 'ambipom', 190);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (425, 'drifloon', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (426, 'drifblim', 425);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (427, 'buneary', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (428, 'lopunny', 427);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (429, 'mismagius', 200);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (430, 'honchkrow', 198);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (431, 'glameow', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (432, 'purugly', 431);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (434, 'stunky', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (435, 'skuntank', 434);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (436, 'bronzor', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (437, 'bronzong', 436);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (441, 'chatot', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (442, 'spiritomb', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (443, 'gible', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (444, 'gabite', 443);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (445, 'garchomp', 444);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (447, 'riolu', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (448, 'lucario', 447);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (449, 'hippopotas', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (450, 'hippowdon', 449);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (451, 'skorupi', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (452, 'drapion', 451);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (453, 'croagunk', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (454, 'toxicroak', 453);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (455, 'carnivine', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (456, 'finneon', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (457, 'lumineon', 456);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (459, 'snover', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (460, 'abomasnow', 459);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (461, 'weavile', 215);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (462, 'magnezone', 82);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (463, 'lickilicky', 108);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (464, 'rhyperior', 112);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (465, 'tangrowth', 114);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (466, 'electivire', 125);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (467, 'magmortar', 126);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (468, 'togekiss', 176);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (469, 'yanmega', 193);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (470, 'leafeon', 133);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (471, 'glaceon', 133);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (472, 'gliscor', 207);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (473, 'mamoswine', 221);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (474, 'porygon-z', 233);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (475, 'gallade', 281);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (476, 'probopass', 299);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (477, 'dusknoir', 356);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (478, 'froslass', 361);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (479, 'rotom', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (480, 'uxie', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (481, 'mesprit', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (482, 'azelf', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (483, 'dialga', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (484, 'palkia', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (485, 'heatran', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (486, 'regigigas', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (487, 'giratina', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (488, 'cresselia', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (489, 'phione', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (490, 'manaphy', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (491, 'darkrai', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (492, 'shaymin', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (493, 'arceus', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (494, 'victini', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (495, 'snivy', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (496, 'servine', 495);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (497, 'serperior', 496);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (498, 'tepig', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (499, 'pignite', 498);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (500, 'emboar', 499);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (501, 'oshawott', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (502, 'dewott', 501);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (503, 'samurott', 502);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (504, 'patrat', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (505, 'watchog', 504);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (506, 'lillipup', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (507, 'herdier', 506);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (508, 'stoutland', 507);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (509, 'purrloin', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (510, 'liepard', 509);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (511, 'pansage', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (512, 'simisage', 511);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (513, 'pansear', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (514, 'simisear', 513);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (515, 'panpour', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (516, 'simipour', 515);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (517, 'munna', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (518, 'musharna', 517);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (519, 'pidove', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (520, 'tranquill', 519);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (521, 'unfezant', 520);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (522, 'blitzle', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (523, 'zebstrika', 522);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (524, 'roggenrola', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (525, 'boldore', 524);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (526, 'gigalith', 525);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (527, 'woobat', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (528, 'swoobat', 527);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (529, 'drilbur', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (530, 'excadrill', 529);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (531, 'audino', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (532, 'timburr', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (533, 'gurdurr', 532);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (534, 'conkeldurr', 533);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (535, 'tympole', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (536, 'palpitoad', 535);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (537, 'seismitoad', 536);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (538, 'throh', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (539, 'sawk', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (540, 'sewaddle', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (541, 'swadloon', 540);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (542, 'leavanny', 541);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (543, 'venipede', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (544, 'whirlipede', 543);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (545, 'scolipede', 544);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (546, 'cottonee', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (547, 'whimsicott', 546);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (548, 'petilil', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (549, 'lilligant', 548);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (550, 'basculin', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (551, 'sandile', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (552, 'krokorok', 551);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (553, 'krookodile', 552);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (554, 'darumaka', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (555, 'darmanitan', 554);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (556, 'maractus', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (557, 'dwebble', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (558, 'crustle', 557);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (559, 'scraggy', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (560, 'scrafty', 559);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (561, 'sigilyph', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (562, 'yamask', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (563, 'cofagrigus', 562);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (564, 'tirtouga', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (565, 'carracosta', 564);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (566, 'archen', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (567, 'archeops', 566);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (568, 'trubbish', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (569, 'garbodor', 568);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (570, 'zorua', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (571, 'zoroark', 570);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (572, 'minccino', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (573, 'cinccino', 572);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (574, 'gothita', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (575, 'gothorita', 574);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (576, 'gothitelle', 575);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (577, 'solosis', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (578, 'duosion', 577);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (579, 'reuniclus', 578);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (580, 'ducklett', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (581, 'swanna', 580);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (582, 'vanillite', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (583, 'vanillish', 582);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (584, 'vanilluxe', 583);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (585, 'deerling', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (586, 'sawsbuck', 585);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (587, 'emolga', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (588, 'karrablast', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (589, 'escavalier', 588);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (590, 'foongus', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (591, 'amoonguss', 590);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (592, 'frillish', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (593, 'jellicent', 592);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (594, 'alomomola', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (595, 'joltik', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (596, 'galvantula', 595);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (597, 'ferroseed', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (598, 'ferrothorn', 597);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (599, 'klink', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (600, 'klang', 599);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (601, 'klinklang', 600);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (602, 'tynamo', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (603, 'eelektrik', 602);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (604, 'eelektross', 603);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (605, 'elgyem', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (606, 'beheeyem', 605);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (607, 'litwick', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (608, 'lampent', 607);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (609, 'chandelure', 608);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (610, 'axew', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (611, 'fraxure', 610);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (612, 'haxorus', 611);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (613, 'cubchoo', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (614, 'beartic', 613);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (615, 'cryogonal', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (616, 'shelmet', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (617, 'accelgor', 616);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (618, 'stunfisk', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (619, 'mienfoo', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (620, 'mienshao', 619);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (621, 'druddigon', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (622, 'golett', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (623, 'golurk', 622);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (624, 'pawniard', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (625, 'bisharp', 624);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (626, 'bouffalant', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (627, 'rufflet', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (628, 'braviary', 627);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (629, 'vullaby', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (630, 'mandibuzz', 629);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (631, 'heatmor', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (632, 'durant', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (633, 'deino', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (634, 'zweilous', 633);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (635, 'hydreigon', 634);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (636, 'larvesta', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (637, 'volcarona', 636);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (638, 'cobalion', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (639, 'terrakion', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (640, 'virizion', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (641, 'tornadus', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (642, 'thundurus', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (643, 'reshiram', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (644, 'zekrom', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (645, 'landorus', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (646, 'kyurem', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (647, 'keldeo', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (648, 'meloetta', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (649, 'genesect', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (650, 'chespin', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (651, 'quilladin', 650);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (652, 'chesnaught', 651);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (653, 'fennekin', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (654, 'braixen', 653);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (655, 'delphox', 654);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (656, 'froakie', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (657, 'frogadier', 656);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (658, 'greninja', 657);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (659, 'bunnelby', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (660, 'diggersby', 659);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (661, 'fletchling', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (662, 'fletchinder', 661);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (663, 'talonflame', 662);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (664, 'scatterbug', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (665, 'spewpa', 664);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (666, 'vivillon', 665);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (667, 'litleo', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (668, 'pyroar', 667);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (669, 'flabebe', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (670, 'floette', 669);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (671, 'florges', 670);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (672, 'skiddo', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (673, 'gogoat', 672);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (674, 'pancham', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (675, 'pangoro', 674);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (676, 'furfrou', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (677, 'espurr', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (678, 'meowstic', 677);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (679, 'honedge', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (680, 'doublade', 679);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (681, 'aegislash', 680);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (682, 'spritzee', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (683, 'aromatisse', 682);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (684, 'swirlix', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (685, 'slurpuff', 684);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (686, 'inkay', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (687, 'malamar', 686);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (688, 'binacle', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (689, 'barbaracle', 688);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (690, 'skrelp', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (691, 'dragalge', 690);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (692, 'clauncher', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (693, 'clawitzer', 692);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (694, 'helioptile', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (695, 'heliolisk', 694);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (696, 'tyrunt', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (697, 'tyrantrum', 696);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (698, 'amaura', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (699, 'aurorus', 698);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (700, 'sylveon', 133);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (701, 'hawlucha', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (702, 'dedenne', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (703, 'carbink', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (704, 'goomy', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (705, 'sliggoo', 704);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (706, 'goodra', 705);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (707, 'klefki', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (708, 'phantump', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (709, 'trevenant', 708);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (710, 'pumpkaboo', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (711, 'gourgeist', 710);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (712, 'bergmite', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (713, 'avalugg', 712);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (714, 'noibat', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (715, 'noivern', 714);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (716, 'xerneas', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (717, 'yveltal', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (718, 'zygarde', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (719, 'diancie', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (720, 'hoopa', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (721, 'volcanion', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (722, 'rowlet', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (723, 'dartrix', 722);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (724, 'decidueye', 723);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (725, 'litten', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (726, 'torracat', 725);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (727, 'incineroar', 726);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (728, 'popplio', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (729, 'brionne', 728);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (730, 'primarina', 729);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (731, 'pikipek', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (732, 'trumbeak', 731);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (733, 'toucannon', 732);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (734, 'yungoos', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (735, 'gumshoos', 734);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (736, 'grubbin', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (737, 'charjabug', 736);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (738, 'vikavolt', 737);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (739, 'crabrawler', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (740, 'crabominable', 739);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (741, 'oricorio', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (742, 'cutiefly', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (743, 'ribombee', 742);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (744, 'rockruff', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (745, 'lycanroc', 744);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (746, 'wishiwashi', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (747, 'mareanie', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (748, 'toxapex', 747);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (749, 'mudbray', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (750, 'mudsdale', 749);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (751, 'dewpider', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (752, 'araquanid', 751);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (753, 'fomantis', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (754, 'lurantis', 753);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (755, 'morelull', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (756, 'shiinotic', 755);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (757, 'salandit', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (758, 'salazzle', 757);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (759, 'stufful', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (760, 'bewear', 759);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (761, 'bounsweet', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (762, 'steenee', 761);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (763, 'tsareena', 762);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (764, 'comfey', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (765, 'oranguru', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (766, 'passimian', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (767, 'wimpod', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (768, 'golisopod', 767);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (769, 'sandygast', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (770, 'palossand', 769);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (771, 'pyukumuku', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (772, 'type-null', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (773, 'silvally', 772);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (774, 'minior', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (775, 'komala', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (776, 'turtonator', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (777, 'togedemaru', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (778, 'mimikyu', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (779, 'bruxish', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (780, 'drampa', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (781, 'dhelmise', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (782, 'jangmo-o', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (783, 'hakamo-o', 782);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (784, 'kommo-o', 783);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (785, 'tapu-koko', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (786, 'tapu-lele', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (787, 'tapu-bulu', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (788, 'tapu-fini', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (789, 'cosmog', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (790, 'cosmoem', 789);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (791, 'solgaleo', 790);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (792, 'lunala', 790);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (793, 'nihilego', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (794, 'buzzwole', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (795, 'pheromosa', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (796, 'xurkitree', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (797, 'celesteela', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (798, 'kartana', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (799, 'guzzlord', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (800, 'necrozma', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (801, 'magearna', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (802, 'marshadow', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (803, 'poipole', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (804, 'naganadel', 803);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (805, 'stakataka', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (806, 'blacephalon', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (807, 'zeraora', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (808, 'meltan', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (809, 'melmetal', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (810, 'grookey', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (811, 'thwackey', 810);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (812, 'rillaboom', 811);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (813, 'scorbunny', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (814, 'raboot', 813);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (815, 'cinderace', 814);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (816, 'sobble', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (817, 'drizzile', 816);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (818, 'inteleon', 817);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (819, 'skwovet', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (820, 'greedent', 819);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (821, 'rookidee', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (822, 'corvisquire', 821);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (823, 'corviknight', 822);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (824, 'blipbug', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (825, 'dottler', 824);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (826, 'orbeetle', 825);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (827, 'nickit', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (828, 'thievul', 827);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (829, 'gossifleur', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (830, 'eldegoss', 829);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (831, 'wooloo', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (832, 'dubwool', 831);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (833, 'chewtle', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (834, 'drednaw', 833);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (835, 'yamper', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (836, 'boltund', 835);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (837, 'rolycoly', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (838, 'carkol', 837);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (839, 'coalossal', 838);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (840, 'applin', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (841, 'flapple', 840);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (842, 'appletun', 840);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (843, 'silicobra', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (844, 'sandaconda', 843);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (845, 'cramorant', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (846, 'arrokuda', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (847, 'barraskewda', 846);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (848, 'toxel', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (849, 'toxtricity', 848);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (850, 'sizzlipede', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (851, 'centiskorch', 850);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (852, 'clobbopus', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (853, 'grapploct', 852);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (854, 'sinistea', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (855, 'polteageist', 854);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (856, 'hatenna', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (857, 'hattrem', 856);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (858, 'hatterene', 857);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (859, 'impidimp', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (860, 'morgrem', 859);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (861, 'grimmsnarl', 860);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (862, 'obstagoon', 264);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (863, 'perrserker', 52);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (864, 'cursola', 222);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (865, 'sirfetchd', 83);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (866, 'mr-rime', 122);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (867, 'runerigus', 562);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (868, 'milcery', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (869, 'alcremie', 868);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (870, 'falinks', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (871, 'pincurchin', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (872, 'snom', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (873, 'frosmoth', 872);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (874, 'stonjourner', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (875, 'eiscue', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (876, 'indeedee', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (877, 'morpeko', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (878, 'cufant', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (879, 'copperajah', 878);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (880, 'dracozolt', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (881, 'arctozolt', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (882, 'dracovish', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (883, 'arctovish', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (884, 'duraludon', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (885, 'dreepy', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (886, 'drakloak', 885);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (887, 'dragapult', 886);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (888, 'zacian', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (889, 'zamazenta', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (890, 'eternatus', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (891, 'kubfu', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (892, 'urshifu', 891);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (893, 'zarude', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (894, 'regieleki', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (895, 'regidrago', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (896, 'glastrier', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (897, 'spectrier', NULL);

INSERT INTO POKEMON_SPECIE (ID_ESPECIE, NAME_SPECIE, ID_PREEVO) 
VALUES (898, 'calyrex', NULL);

