INSERT INTO STATS (ID_STAT, NAME_STATS, IS_BATTLE_ONLY) 
VALUES (1, 'hp', '0');

INSERT INTO STATS (ID_STAT, NAME_STATS, IS_BATTLE_ONLY) 
VALUES (2, 'attack', '0');

INSERT INTO STATS (ID_STAT, NAME_STATS, IS_BATTLE_ONLY) 
VALUES (3, 'defense', '0');

INSERT INTO STATS (ID_STAT, NAME_STATS, IS_BATTLE_ONLY) 
VALUES (4, 'special-attack', '0');

INSERT INTO STATS (ID_STAT, NAME_STATS, IS_BATTLE_ONLY) 
VALUES (5, 'special-defense', '0');

INSERT INTO STATS (ID_STAT, NAME_STATS, IS_BATTLE_ONLY) 
VALUES (6, 'speed', '0');

INSERT INTO STATS (ID_STAT, NAME_STATS, IS_BATTLE_ONLY) 
VALUES (7, 'accuracy', '1');

INSERT INTO STATS (ID_STAT, NAME_STATS, IS_BATTLE_ONLY) 
VALUES (8, 'evasion', '1');
