INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (1, 'normal', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (2, 'fighting', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (3, 'flying', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (4, 'poison', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (5, 'ground', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (6, 'rock', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (7, 'bug', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (8, 'ghost', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (9, 'steel', 2, 2);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (10, 'fire', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (11, 'water', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (12, 'grass', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (13, 'electric', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (14, 'psychic', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (15, 'ice', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (16, 'dragon', 1, 1);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (17, 'dark', 2, 2);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (18, 'fairy', 6, 6);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (10001, 'unknown', 2, 2);

INSERT INTO TYPEMOVE (ID_TYPE, NAME_TYPE, GENERATION, REGION) 
VALUES (10002, 'shadow', 3, 3);

