INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 2, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 3, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 4, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 5, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 6, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 7, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 8, 0);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 9, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 10, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 11, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 12, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 16, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 17, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (1, 18, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 1, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 2, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 3, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 4, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 5, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 6, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 7, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 8, 0);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 9, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 10, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 11, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 12, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 14, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 15, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 16, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 17, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (2, 18, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 2, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 3, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 4, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 5, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 6, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 7, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 8, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 9, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 10, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 11, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 12, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 13, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 16, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 17, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (3, 18, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 2, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 3, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 4, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 5, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 6, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 7, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 8, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 9, 0);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 10, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 11, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 12, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 16, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 17, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (4, 18, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 2, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 3, 0);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 4, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 5, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 6, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 7, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 8, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 9, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 10, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 11, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 12, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 13, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 16, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 17, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (5, 18, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 2, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 3, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 4, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 5, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 6, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 7, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 8, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 9, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 10, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 11, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 12, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 15, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 16, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 17, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (6, 18, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 2, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 3, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 4, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 5, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 6, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 7, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 8, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 9, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 10, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 11, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 12, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 14, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 16, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 17, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (7, 18, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 1, 0);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 2, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 3, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 4, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 5, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 6, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 7, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 8, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 9, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 10, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 11, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 12, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 14, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 16, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 17, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (8, 18, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 2, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 3, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 4, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 5, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 6, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 7, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 8, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 9, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 10, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 11, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 12, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 13, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 15, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 16, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 17, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (9, 18, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 2, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 3, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 4, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 5, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 6, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 7, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 8, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 9, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 10, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 11, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 12, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 15, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 16, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 17, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (10, 18, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 2, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 3, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 4, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 5, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 6, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 7, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 8, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 9, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 10, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 11, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 12, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 16, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 17, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (11, 18, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 2, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 3, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 4, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 5, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 6, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 7, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 8, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 9, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 10, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 11, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 12, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 16, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 17, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (12, 18, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 2, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 3, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 4, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 5, 0);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 6, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 7, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 8, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 9, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 10, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 11, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 12, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 13, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 16, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 17, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (13, 18, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 2, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 3, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 4, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 5, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 6, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 7, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 8, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 9, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 10, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 11, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 12, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 14, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 16, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 17, 0);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (14, 18, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 2, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 3, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 4, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 5, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 6, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 7, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 8, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 9, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 10, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 11, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 12, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 15, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 16, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 17, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (15, 18, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 2, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 3, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 4, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 5, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 6, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 7, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 8, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 9, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 10, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 11, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 12, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 16, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 17, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (16, 18, 0);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 2, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 3, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 4, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 5, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 6, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 7, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 8, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 9, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 10, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 11, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 12, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 14, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 16, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 17, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (17, 18, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 1, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 2, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 3, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 4, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 5, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 6, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 7, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 8, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 9, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 10, 50);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 11, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 12, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 13, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 14, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 15, 100);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 16, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 17, 200);

INSERT INTO TYPE_EFFICACY (DAMAGE_TYPE, TARGET_TYPE, DAMAGE_FACTOR) 
VALUES (18, 18, 100);

