INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (1, 4, 'canalave-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (2, 4, 'eterna-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (3, 4, 'pastoria-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (4, 4, 'sunyshore-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (5, 4, 'sinnoh-pokemon-league');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (6, 4, 'oreburgh-mine');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (7, 4, 'valley-windworks');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (8, 4, 'eterna-forest');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (9, 4, 'fuego-ironworks');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (10, 4, 'mt-coronet');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (11, 4, 'great-marsh');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (12, 4, 'solaceon-ruins');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (13, 4, 'sinnoh-victory-road');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (14, 4, 'ravaged-path');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (15, 4, 'oreburgh-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (16, 4, 'stark-mountain');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (17, 4, 'spring-path');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (18, 4, 'turnback-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (19, 4, 'snowpoint-temple');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (20, 4, 'wayward-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (22, 4, 'ruin-maniac-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (23, 4, 'trophy-garden');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (24, 4, 'iron-island');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (25, 4, 'old-chateau');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (26, 4, 'lake-verity');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (27, 4, 'lake-valor');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (28, 4, 'lake-acuity');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (29, 4, 'valor-lakefront');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (30, 4, 'acuity-lakefront');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (31, 4, 'sinnoh-route-201');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (32, 4, 'sinnoh-route-202');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (33, 4, 'sinnoh-route-203');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (34, 4, 'sinnoh-route-204');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (35, 4, 'sinnoh-route-205');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (36, 4, 'sinnoh-route-206');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (37, 4, 'sinnoh-route-207');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (38, 4, 'sinnoh-route-208');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (39, 4, 'sinnoh-route-209');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (40, 4, 'lost-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (41, 4, 'sinnoh-route-210');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (42, 4, 'sinnoh-route-211');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (43, 4, 'sinnoh-route-212');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (44, 4, 'sinnoh-route-213');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (45, 4, 'sinnoh-route-214');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (46, 4, 'sinnoh-route-215');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (47, 4, 'sinnoh-route-216');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (48, 4, 'sinnoh-route-217');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (49, 4, 'sinnoh-route-218');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (50, 4, 'sinnoh-route-219');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (51, 4, 'sinnoh-route-221');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (52, 4, 'sinnoh-route-222');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (53, 4, 'sinnoh-route-224');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (54, 4, 'sinnoh-route-225');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (55, 4, 'sinnoh-route-227');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (56, 4, 'sinnoh-route-228');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (57, 4, 'sinnoh-route-229');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (58, 4, 'twinleaf-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (59, 4, 'celestic-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (60, 4, 'resort-area');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (61, 4, 'sinnoh-sea-route-220');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (62, 4, 'sinnoh-sea-route-223');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (63, 4, 'sinnoh-sea-route-226');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (64, 4, 'sinnoh-sea-route-230');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (65, 2, 'blackthorn-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (66, 2, 'burned-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (67, 1, 'celadon-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (68, 1, 'cerulean-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (69, 2, 'cherrygrove-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (70, 2, 'cianwood-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (71, 1, 'cinnabar-island');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (72, 2, 'dark-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (73, 1, 'digletts-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (74, 2, 'dragons-den');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (75, 2, 'ecruteak-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (76, 1, 'fuchsia-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (77, 2, 'ice-path');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (78, 2, 'ilex-forest');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (79, 2, 'lake-of-rage');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (80, 1, 'mt-moon');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (81, 2, 'mt-mortar');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (82, 2, 'mt-silver');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (83, 2, 'national-park');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (84, 2, 'new-bark-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (85, 2, 'olivine-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (86, 1, 'pallet-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (87, 1, 'rock-tunnel');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (88, 1, 'kanto-route-1');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (89, 1, 'kanto-route-10');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (90, 1, 'kanto-route-11');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (91, 1, 'kanto-route-12');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (92, 1, 'kanto-route-13');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (93, 1, 'kanto-route-14');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (94, 1, 'kanto-route-15');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (95, 1, 'kanto-route-16');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (96, 1, 'kanto-route-17');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (97, 1, 'kanto-route-18');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (98, 1, 'kanto-sea-route-19');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (99, 1, 'kanto-route-2');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (100, 1, 'kanto-sea-route-20');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (101, 1, 'kanto-sea-route-21');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (102, 1, 'kanto-route-22');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (103, 1, 'kanto-route-24');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (104, 1, 'kanto-route-25');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (105, 1, 'kanto-route-26');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (106, 1, 'kanto-route-27');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (107, 1, 'kanto-route-28');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (108, 2, 'johto-route-29');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (109, 1, 'kanto-route-3');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (110, 2, 'johto-route-30');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (111, 2, 'johto-route-31');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (112, 2, 'johto-route-32');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (113, 2, 'johto-route-33');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (114, 2, 'johto-route-34');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (115, 2, 'johto-route-35');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (116, 2, 'johto-route-36');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (117, 2, 'johto-route-37');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (118, 2, 'johto-route-38');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (119, 2, 'johto-route-39');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (120, 1, 'kanto-route-4');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (121, 2, 'johto-sea-route-40');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (122, 2, 'johto-sea-route-41');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (123, 2, 'johto-route-42');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (124, 2, 'johto-route-43');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (125, 2, 'johto-route-44');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (126, 2, 'johto-route-45');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (127, 2, 'johto-route-46');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (128, 2, 'johto-route-47');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (129, 2, 'johto-route-48');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (130, 1, 'kanto-route-5');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (131, 1, 'kanto-route-6');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (132, 1, 'kanto-route-7');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (133, 1, 'kanto-route-8');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (134, 1, 'kanto-route-9');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (135, 2, 'ruins-of-alph');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (136, 1, 'seafoam-islands');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (137, 2, 'slowpoke-well');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (138, 2, 'sprout-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (139, 2, 'bell-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (140, 2, 'tohjo-falls');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (141, 2, 'union-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (147, 1, 'cerulean-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (148, 2, 'unknown-all-poliwag');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (149, 2, 'unknown-all-rattata');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (150, 2, 'unknown-all-bugs');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (151, 1, 'vermilion-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (152, 1, 'kanto-victory-road-1');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (153, 2, 'violet-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (154, 1, 'viridian-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (155, 1, 'viridian-forest');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (156, 2, 'whirl-islands');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (157, 1, 'kanto-route-23');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (158, 1, 'power-plant');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (159, 1, 'kanto-victory-road-2');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (160, 1, 'pokemon-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (161, 1, 'pokemon-mansion');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (162, 1, 'kanto-safari-zone');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (163, 4, 'sandgem-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (164, 4, 'floaroma-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (165, 4, 'solaceon-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (167, 4, 'jubilife-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (168, 4, 'oreburgh-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (169, 4, 'hearthome-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (170, 4, 'veilstone-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (171, 4, 'snowpoint-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (172, 4, 'spear-pillar');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (173, 4, 'pal-park');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (174, 4, 'amity-square');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (175, 4, 'floaroma-meadow');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (177, 4, 'fullmoon-island');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (178, 4, 'sendoff-spring');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (179, 4, 'flower-paradise');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (180, 4, 'maniac-tunnel');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (181, 4, 'galactic-hq');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (182, 4, 'verity-lakefront');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (183, 4, 'newmoon-island');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (184, 4, 'sinnoh-battle-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (185, 4, 'fight-area');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (186, 4, 'survival-area');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (187, 4, 'seabreak-path');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (188, 4, 'sinnoh-hall-of-origin-1');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (189, 4, 'sinnoh-hall-of-origin-2');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (190, 4, 'verity-cavern');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (191, 4, 'valor-cavern');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (192, 4, 'acuity-cavern');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (193, 4, 'jubilife-tv');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (194, 4, 'poketch-co');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (195, 4, 'gts');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (196, 4, 'trainers-school');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (197, 4, 'mining-museum');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (198, 4, 'sinnoh-flower-shop');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (199, 4, 'sinnoh-cycle-shop');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (200, 4, 'contest-hall');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (201, 4, 'poffin-house');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (202, 4, 'sinnoh-foreign-building');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (203, 4, 'pokemon-day-care');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (204, 4, 'veilstone-store');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (205, 4, 'sinnoh-game-corner');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (206, 4, 'canalave-library');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (207, 4, 'vista-lighthouse');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (208, 4, 'sunyshore-market');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (209, 4, 'footstep-house');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (210, 4, 'sinnoh-cafe');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (211, 4, 'grand-lake');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (212, 4, 'sinnoh-restaurant');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (213, 4, 'battle-park');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (214, 4, 'battle-frontier');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (215, 4, 'battle-factory');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (216, 4, 'battle-castle');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (217, 4, 'battle-arcade');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (218, 4, 'battle-hall');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (219, 4, 'distortion-world');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (220, 4, 'sinnoh-global-terminal');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (221, 4, 'sinnoh-villa');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (222, 4, 'battleground');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (223, 4, 'rotoms-room');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (224, 4, 'tg-eterna-bldg');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (225, 4, 'iron-ruins');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (226, 4, 'iceberg-ruins');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (227, 4, 'rock-peak-ruins');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (228, 2, 'azalea-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (229, 2, 'goldenrod-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (230, 2, 'mahogany-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (231, 1, 'pewter-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (232, 1, 'lavender-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (233, 1, 'indigo-plateau');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (234, 1, 'saffron-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (236, 2, 'johto-lighthouse');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (237, 2, 'team-rocket-hq');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (238, 2, 'goldenrod-tunnel');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (239, 2, 'mt-silver-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (241, 2, 'pokeathlon-dome');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (242, 2, 'ss-aqua');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (243, 2, 'safari-zone-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (244, 2, 'cliff-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (245, 2, 'frontier-access');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (246, 2, 'bellchime-trail');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (247, 2, 'sinjoh-ruins');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (248, 2, 'embedded-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (249, 2, 'pokewalker');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (250, 2, 'cliff-edge-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (252, 2, 'radio-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (253, NULL, 'day-care-couple');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (254, NULL, 'link-trade-arrive');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (255, NULL, 'link-trade-met');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (256, NULL, 'kanto');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (257, NULL, 'johto');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (258, NULL, 'hoenn');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (259, NULL, 'sinnoh');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (260, NULL, 'distant-land');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (261, NULL, 'traveling-man');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (262, NULL, 'riley');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (263, NULL, 'cynthia');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (264, NULL, 'mystery-zone');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (265, NULL, 'lovely-place');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (266, NULL, 'pokemon-ranger');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (267, NULL, 'faraway-place');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (268, NULL, 'pokemon-movie');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (269, NULL, 'pokemon-movie-06');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (270, NULL, 'pokemon-movie-07');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (271, NULL, 'pokemon-movie-08');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (272, NULL, 'pokemon-movie-09');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (273, NULL, 'pokemon-movie-10');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (274, NULL, 'pokemon-movie-11');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (275, NULL, 'pokemon-movie-12');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (276, NULL, 'pokemon-movie-13');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (277, NULL, 'pokemon-movie-14');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (278, NULL, 'pokemon-movie-15');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (279, NULL, 'pokemon-movie-16');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (280, NULL, 'pokemon-cartoon');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (281, NULL, 'space-world');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (282, NULL, 'space-world-06');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (283, NULL, 'space-world-07');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (284, NULL, 'space-world-08');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (285, NULL, 'space-world-09');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (286, NULL, 'space-world-10');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (287, NULL, 'space-world-11');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (288, NULL, 'space-world-12');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (289, NULL, 'space-world-13');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (290, NULL, 'space-world-14');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (291, NULL, 'space-world-15');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (292, NULL, 'space-world-16');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (293, NULL, 'pokemon-festa');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (294, NULL, 'pokemon-festa-06');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (295, NULL, 'pokemon-festa-07');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (296, NULL, 'pokemon-festa-08');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (297, NULL, 'pokemon-festa-09');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (298, NULL, 'pokemon-festa-10');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (299, NULL, 'pokemon-festa-11');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (300, NULL, 'pokemon-festa-12');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (301, NULL, 'pokemon-festa-13');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (302, NULL, 'pokemon-festa-14');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (303, NULL, 'pokemon-festa-15');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (304, NULL, 'pokemon-festa-16');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (305, NULL, 'pokepark');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (306, NULL, 'pokepark-06');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (307, NULL, 'pokepark-07');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (308, NULL, 'pokepark-08');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (309, NULL, 'pokepark-09');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (310, NULL, 'pokepark-10');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (311, NULL, 'pokepark-11');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (312, NULL, 'pokepark-12');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (313, NULL, 'pokepark-13');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (314, NULL, 'pokepark-14');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (315, NULL, 'pokepark-15');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (316, NULL, 'pokepark-16');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (317, NULL, 'pokemon-center');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (318, NULL, 'pc-tokyo');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (319, NULL, 'pc-osaka');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (320, NULL, 'pc-fukuoka');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (321, NULL, 'pc-nagoya');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (322, NULL, 'pc-sapporo');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (323, NULL, 'pc-yokohama');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (324, NULL, 'nintendo-world');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (325, NULL, 'pokemon-event');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (326, NULL, 'pokemon-event-06');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (327, NULL, 'pokemon-event-07');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (328, NULL, 'pokemon-event-08');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (329, NULL, 'pokemon-event-09');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (330, NULL, 'pokemon-event-10');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (331, NULL, 'pokemon-event-11');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (332, NULL, 'pokemon-event-12');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (333, NULL, 'pokemon-event-13');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (334, NULL, 'pokemon-event-14');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (335, NULL, 'pokemon-event-15');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (336, NULL, 'pokemon-event-16');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (337, NULL, 'wi-fi-event');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (338, NULL, 'wi-fi-gift');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (339, NULL, 'pokemon-fan-club');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (340, NULL, 'event-site');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (341, NULL, 'concert-event');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (342, NULL, 'mr-pokemon');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (343, NULL, 'primo');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (344, 5, 'unova-mystery-zone');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (345, 5, 'unova-faraway-place');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (346, 5, 'nuvema-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (347, 5, 'accumula-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (348, 5, 'striaton-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (349, 5, 'nacrene-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (350, 5, 'castelia-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (351, 5, 'nimbasa-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (352, 5, 'driftveil-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (353, 5, 'mistralton-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (354, 5, 'icirrus-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (355, 5, 'opelucid-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (356, 5, 'unova-route-1');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (357, 5, 'unova-route-2');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (358, 5, 'unova-route-3');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (359, 5, 'unova-route-4');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (360, 5, 'unova-route-5');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (361, 5, 'unova-route-6');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (362, 5, 'unova-route-7');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (363, 5, 'unova-route-8');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (364, 5, 'unova-route-9');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (365, 5, 'unova-route-10');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (366, 5, 'unova-route-11');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (367, 5, 'unova-route-12');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (368, 5, 'unova-route-13');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (369, 5, 'unova-route-14');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (370, 5, 'unova-route-15');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (371, 5, 'unova-route-16');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (372, 5, 'unova-route-17');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (373, 5, 'unova-route-18');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (374, 5, 'dreamyard');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (375, 5, 'pinwheel-forest');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (376, 5, 'desert-resort');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (377, 5, 'relic-castle');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (378, 5, 'cold-storage');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (379, 5, 'chargestone-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (380, 5, 'twist-mountain');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (381, 5, 'dragonspiral-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (382, 5, 'unova-victory-road');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (383, 5, 'lacunosa-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (384, 5, 'undella-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (385, 5, 'anville-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (386, 5, 'unova-pokemon-league');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (387, 5, 'ns-castle');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (388, 5, 'royal-unova');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (389, 5, 'gear-station');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (390, 5, 'battle-subway');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (391, 5, 'musical-theater');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (392, 5, 'black-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (393, 5, 'white-forest');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (394, 5, 'unity-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (395, 5, 'wellspring-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (396, 5, 'mistralton-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (397, 5, 'rumination-field');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (398, 5, 'celestial-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (399, 5, 'moor-of-icirrus');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (400, 5, 'unova-shopping-mall');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (401, 5, 'challengers-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (402, 5, 'poke-transfer-lab');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (403, 5, 'giant-chasm');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (404, 5, 'liberty-garden');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (405, 5, 'p2-laboratory');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (406, 5, 'skyarrow-bridge');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (407, 5, 'driftveil-drawbridge');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (408, 5, 'tubeline-bridge');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (409, 5, 'village-bridge');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (410, 5, 'marvelous-bridge');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (411, 5, 'entralink');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (412, 5, 'abundant-shrine');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (413, 5, 'undella-bay');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (414, 5, 'lostlorn-forest');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (415, 5, 'trial-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (416, 5, 'guidance-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (417, 5, 'entree-forest');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (418, 5, 'accumula-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (419, 5, 'undella-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (420, 5, 'nacrene-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (421, 5, 'castelia-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (422, 5, 'nimbasa-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (423, 5, 'opelucid-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (424, 5, 'black-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (425, 5, 'white-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (426, 5, 'bridge-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (427, 5, 'route-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (428, 5, 'abyssal-ruins');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (429, 3, 'petalburg-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (430, 3, 'slateport-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (431, 3, 'lilycove-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (432, 3, 'mossdeep-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (433, 3, 'sootopolis-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (434, 3, 'ever-grande-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (435, 3, 'meteor-falls');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (436, 3, 'rusturf-tunnel');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (437, 3, 'granite-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (438, 3, 'petalburg-woods');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (439, 3, 'jagged-pass');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (440, 3, 'fiery-path');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (441, 3, 'mt-pyre');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (442, 3, 'seafloor-cavern');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (443, 3, 'cave-of-origin');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (444, 3, 'hoenn-victory-road');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (445, 3, 'shoal-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (446, 3, 'new-mauville');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (447, 3, 'abandoned-ship');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (448, 3, 'sky-pillar');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (449, 3, 'hoenn-route-101');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (450, 3, 'hoenn-route-102');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (451, 3, 'hoenn-route-103');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (452, 3, 'hoenn-route-104');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (453, 3, 'hoenn-route-105');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (454, 3, 'hoenn-route-106');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (455, 3, 'hoenn-route-107');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (456, 3, 'hoenn-route-108');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (457, 3, 'hoenn-route-109');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (458, 3, 'hoenn-route-110');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (459, 3, 'hoenn-route-111');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (460, 3, 'hoenn-route-112');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (461, 3, 'hoenn-route-113');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (462, 3, 'hoenn-route-114');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (463, 3, 'hoenn-route-115');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (464, 3, 'hoenn-route-116');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (465, 3, 'hoenn-route-117');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (466, 3, 'hoenn-route-118');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (467, 3, 'hoenn-route-119');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (468, 3, 'hoenn-route-120');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (469, 3, 'hoenn-route-121');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (470, 3, 'hoenn-route-122');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (471, 3, 'hoenn-route-123');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (472, 3, 'hoenn-route-124');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (473, 3, 'hoenn-route-125');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (474, 3, 'hoenn-route-126');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (475, 3, 'hoenn-route-127');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (476, 3, 'hoenn-route-128');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (477, 3, 'hoenn-route-129');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (478, 3, 'hoenn-route-130');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (479, 3, 'hoenn-route-131');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (480, 3, 'hoenn-route-132');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (481, 3, 'hoenn-route-133');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (482, 3, 'hoenn-route-134');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (483, 3, 'hoenn-safari-zone');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (484, 3, 'dewford-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (485, 3, 'pacifidlog-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (486, 3, 'magma-hideout');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (487, 3, 'mirage-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (488, 3, 'desert-underpass');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (489, 3, 'artisan-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (490, 3, 'hoenn-altering-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (491, 1, 'monean-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (492, 1, 'liptoo-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (493, 1, 'weepth-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (494, 1, 'dilford-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (495, 1, 'scufib-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (496, 1, 'rixy-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (497, 1, 'viapos-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (498, 1, 'ss-anne');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (500, 1, 'mt-ember');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (501, 1, 'berry-forest');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (502, 1, 'icefall-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (503, 1, 'pattern-bush');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (504, 1, 'lost-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (505, 1, 'kindle-road');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (506, 1, 'treasure-beach');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (507, 1, 'cape-brink');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (508, 1, 'bond-bridge');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (509, 1, 'three-isle-port');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (510, 1, 'resort-gorgeous');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (511, 1, 'water-labyrinth');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (512, 1, 'five-isle-meadow');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (513, 1, 'memorial-pillar');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (514, 1, 'outcast-island');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (515, 1, 'green-path');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (516, 1, 'water-path');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (517, 1, 'ruin-valley');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (518, 1, 'trainer-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (519, 1, 'canyon-entrance');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (520, 1, 'sevault-canyon');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (521, 1, 'tanoby-ruins');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (526, 1, 'one-island');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (527, 1, 'four-island');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (528, 1, 'five-island');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (529, 1, 'kanto-altering-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (531, 5, 'aspertia-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (532, 5, 'virbank-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (533, 5, 'humilau-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (534, 5, 'pokestar-studios');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (535, 5, 'join-avenue');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (536, 5, 'floccesy-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (537, 5, 'lentimas-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (538, 5, 'unova-route-19');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (539, 5, 'unova-route-20');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (540, 5, 'unova-route-21');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (541, 5, 'unova-route-22');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (542, 5, 'unova-route-23');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (543, 5, 'castelia-sewers');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (544, 5, 'floccesy-ranch');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (545, 5, 'virbank-complex');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (546, 5, 'reversal-mountain');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (547, 5, 'strange-house');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (548, 5, 'unova-victory-road-2');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (549, 5, 'plasma-frigate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (550, 5, 'relic-passage');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (551, 5, 'clay-tunnel');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (552, 5, 'white-treehollow');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (553, 5, 'black-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (554, 5, 'seaside-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (555, 5, 'cave-of-being');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (556, 5, 'hidden-grotto');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (557, 5, 'marine-tube');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (558, 5, 'virbank-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (559, 5, 'aspertia-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (560, 5, 'nature-sanctuary');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (561, 5, 'medal-secretariat');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (562, 5, 'underground-ruins');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (563, 5, 'rocky-mountain-room');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (564, 5, 'glacier-room');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (565, 5, 'iron-room');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (566, 5, 'pledge-grove');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (567, 3, 'littleroot-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (568, 3, 'oldale-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (569, 3, 'lavaridge-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (570, 3, 'fallarbor-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (571, 3, 'verdanturf-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (572, 3, 'mauville-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (573, 3, 'rustboro-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (574, 3, 'fortree-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (575, 3, 'underwater');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (576, 3, 'mt-chimney');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (577, 3, 'mirage-island');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (578, 3, 'southern-island');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (579, 3, 'sealed-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (580, 3, 'scorched-slab');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (581, 3, 'island-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (582, 3, 'desert-ruins');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (583, 3, 'ancient-tomb');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (584, 3, 'inside-of-truck');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (585, 3, 'secret-base');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (586, 3, 'hoenn-battle-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (587, 6, 'vaniville-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (588, 6, 'kalos-route-1');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (589, 6, 'vaniville-pathway');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (590, 6, 'aquacorde-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (591, 6, 'kalos-route-2');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (592, 6, 'avance-trail');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (593, 6, 'santalune-forest');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (594, 6, 'kalos-route-3');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (595, 6, 'ouvert-way');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (596, 6, 'santalune-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (597, 6, 'kalos-route-4');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (598, 6, 'parterre-way');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (599, 6, 'lumiose-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (600, 6, 'prism-tower');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (601, 6, 'lysandre-labs');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (602, 6, 'kalos-route-5');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (603, 6, 'versant-road');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (604, 6, 'camphrier-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (605, 6, 'shabboneau-castle');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (606, 6, 'kalos-route-6');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (607, 6, 'palais-lane');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (608, 6, 'parfum-palace');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (609, 6, 'kalos-route-7');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (610, 6, 'riviÃ¨re-walk');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (611, 6, 'cyllage-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (612, 6, 'kalos-route-8');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (613, 6, 'muraille-coast');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (614, 6, 'ambrette-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (615, 6, 'kalos-route-9');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (616, 6, 'spikes-passage');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (617, 6, 'battle-chateau');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (618, 6, 'kalos-route-10');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (619, 6, 'menhir-trail');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (620, 6, 'geosenge-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (621, 6, 'kalos-route-11');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (622, 6, 'miroir-way');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (623, 6, 'reflection-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (624, 6, 'shalour-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (625, 6, 'tower-of-mastery');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (626, 6, 'kalos-route-12');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (627, 6, 'fourrage-road');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (628, 6, 'coumarine-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (629, 6, 'kalos-route-13');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (630, 6, 'lumiose-badlands');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (631, 6, 'kalos-route-14');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (632, 6, 'laverre-nature-trail');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (633, 6, 'laverre-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (634, 6, 'poke-ball-factory');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (635, 6, 'kalos-route-15');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (636, 6, 'brun-way');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (637, 6, 'dendemille-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (638, 6, 'kalos-route-16');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (639, 6, 'melancolie-path');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (640, 6, 'frost-cavern');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (641, 6, 'kalos-route-17');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (642, 6, 'mamoswine-road');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (643, 6, 'anistar-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (644, 6, 'kalos-route-18');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (645, 6, 'vallee-etroite-way');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (646, 6, 'couriway-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (647, 6, 'kalos-route-19');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (648, 6, 'grande-vallee-way');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (649, 6, 'snowbelle-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (650, 6, 'kalos-route-20');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (651, 6, 'winding-woods');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (652, 6, 'pokemon-village');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (653, 6, 'kalos-route-21');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (654, 6, 'derniÃ¨re-way');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (655, 6, 'kalos-route-22');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (656, 6, 'detourner-way');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (657, 6, 'kalos-victory-road');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (658, 6, 'kalos-pokemon-league');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (659, 6, 'kiloude-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (660, 6, 'battle-maison');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (661, 6, 'azure-bay');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (662, 6, 'dendemille-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (663, 6, 'couriway-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (664, 6, 'ambrette-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (665, 6, 'lumiose-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (666, 6, 'shalour-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (667, 6, 'coumarine-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (668, 6, 'laverre-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (669, 6, 'anistar-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (670, 6, 'snowbelle-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (671, 6, 'glittering-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (672, 6, 'connecting-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (673, 6, 'zubat-roost');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (674, 6, 'kalos-power-plant');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (675, 6, 'team-flare-secret-hq');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (676, 6, 'terminus-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (677, 6, 'lost-hotel');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (678, 6, 'chamber-of-emptiness');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (679, 6, 'sea-spirits-den');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (680, 6, 'friend-safari');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (681, 6, 'blazing-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (682, 6, 'flood-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (683, 6, 'ironworks-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (684, 6, 'dragonmark-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (685, 6, 'radiant-chamber');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (686, 6, 'pokemon-league-gate');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (687, 6, 'lumiose-station');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (688, 6, 'kiloude-station');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (689, 6, 'ambrette-aquarium');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (690, 6, 'unknown-dungeon');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (691, 3, 'hoenn-pokemon-league');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (692, 3, 'team-aqua-hideout');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (693, 3, 'sea-mauville');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (694, 3, 'team-magma-hideout');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (695, 3, 'battle-resort');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (696, 3, 'ss-tidal');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (697, 3, 'mirage-forest');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (698, 3, 'mirage-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (699, 3, 'mirage-mountain');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (700, 3, 'trackless-forest');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (701, 3, 'pathless-plain');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (702, 3, 'nameless-cavern');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (703, 3, 'fabled-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (704, 3, 'gnarled-den');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (705, 3, 'crescent-isle');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (706, 3, 'secret-islet');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (707, 3, 'soaring-in-the-sky');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (708, 3, 'secret-shore');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (709, 3, 'secret-meadow');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (710, 7, 'alola-route-1--hauoli-outskirts');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (711, 7, 'alola-route-1');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (712, 7, 'alola-route-3');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (713, 7, 'alola-route-2');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (714, 7, 'kalae-bay');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (715, 7, 'melemele-sea');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (716, 7, 'hauoli-city--beachfront');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (717, 7, 'hauoli-city--shopping-district');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (718, 7, 'hauoli-city--marina');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (719, 7, 'iki-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (720, 7, 'mahalo-trail');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (721, 7, 'mahalo-trail--plank-bridge');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (722, 7, 'ruins-of-conflict');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (723, 7, 'ten-carat-hill');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (724, 7, 'ten-carat-hill--farthest-hollow');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (725, 7, 'hauoli-cemetery');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (726, 7, 'melemele-meadow');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (727, 7, 'seaward-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (728, 7, 'berry-fields');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (729, 7, 'verdant-cavern--trial-site');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (730, 7, 'verdant-cavern--totems-den');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (731, 7, 'alola-route-4');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (732, 7, 'alola-route-5');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (733, 7, 'alola-route-6');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (734, 7, 'alola-route-7');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (735, 7, 'alola-route-8');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (736, 7, 'alola-route-9');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (737, 7, 'hano-grand-resort');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (738, 7, 'hano-beach');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (739, 7, 'akala-meadow');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (740, 7, 'paniola-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (741, 7, 'heahea-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (742, 7, 'konikoni-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (743, 7, 'royal-avenue');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (744, 7, 'memorial-hill');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (745, 7, 'paniola-ranch');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (746, 7, 'wela-volcano-park');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (747, 7, 'wela-volcano-park--totems-den');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (748, 7, 'brooklet-hill');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (749, 7, 'brooklet-hill--totems-den');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (750, 7, 'lush-jungle');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (751, 7, 'ruins-of-life');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (752, 7, 'akala-outskirts');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (753, 7, 'digletts-tunnel');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (754, 7, 'battle-royal-dome');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (755, 7, 'alola-route-10');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (756, 7, 'alola-route-11');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (757, 7, 'secluded-shore');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (758, 7, 'alola-route-13');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (759, 7, 'tapu-village');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (760, 7, 'alola-route-15');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (761, 7, 'alola-route-16');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (762, 7, 'alola-route-17');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (763, 7, 'alola-route-12');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (764, 7, 'haina-desert');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (765, 7, 'alola-route-14');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (766, 7, 'ulaula-meadow');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (767, 7, 'po-town');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (768, 7, 'malie-city');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (769, 7, 'malie-garden');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (770, 7, 'mount-hokulani');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (771, 7, 'blush-mountain');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (772, 7, 'ruins-of-abundance');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (773, 7, 'lake-of-the-sunne');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (774, 7, 'lake-of-the-moone');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (775, 7, 'mount-lanakila');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (776, 7, 'shady-house');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (777, 7, 'thrifty-megamart--abandoned-site');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (778, 7, 'hokulani-observatory');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (779, 7, 'alola-pokemon-league');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (780, 7, 'poni-meadow');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (781, 7, 'poni-wilds');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (782, 7, 'ancient-poni-path');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (783, 7, 'poni-breaker-coast');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (784, 7, 'poni-grove');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (785, 7, 'poni-plains');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (786, 7, 'poni-coast');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (787, 7, 'poni-gauntlet');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (788, 7, 'seafolk-village');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (789, 7, 'vast-poni-canyon');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (790, 7, 'altar-of-the-sunne');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (791, 7, 'altar-of-the-moone');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (792, 7, 'ruins-of-hope');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (793, 7, 'resolution-cave');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (794, 7, 'exeggutor-island');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (795, 7, 'battle-tree');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (796, 7, 'aether-paradise');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (797, 7, 'ultra-space');

INSERT INTO LOCATION_P (ID_LOCATION, REGION, NAME_L) 
VALUES (798, 7, 'malie-city--outer-cape');

