
INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (234, 'intrepid-sword', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (235, 'dauntless-shield', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (236, 'libero', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (237, 'ball-fetch', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (238, 'cotton-down', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (239, 'propeller-tail', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (240, 'mirror-armor', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (241, 'gulp-missile', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (242, 'stalwart', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (243, 'steam-engine', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (244, 'punk-rock', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (245, 'sand-spit', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (246, 'ice-scales', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (247, 'ripen', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (248, 'ice-face', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (249, 'power-spot', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (250, 'mimicry', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (251, 'screen-cleaner', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (252, 'steely-spirit', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (253, 'perish-body', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (254, 'wandering-spirit', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (255, 'gorilla-tactics', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (256, 'neutralizing-gas', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (257, 'pastel-veil', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (258, 'hunger-switch', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (259, 'quick-draw', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (260, 'unseen-fist', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (261, 'curious-medicine', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (262, 'transistor', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (263, 'dragons-maw', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (264, 'chilling-neigh', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (265, 'grim-neigh', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (266, 'as-one-glastrier', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (267, 'as-one-spectrier', 8);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (192, 'stamina', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (193, 'wimp-out', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (194, 'emergency-exit', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (195, 'water-compaction', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (196, 'merciless', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (197, 'shields-down', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (198, 'stakeout', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (199, 'water-bubble', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (200, 'steelworker', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (201, 'berserk', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (202, 'slush-rush', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (203, 'long-reach', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (204, 'liquid-voice', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (205, 'triage', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (206, 'galvanize', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (207, 'surge-surfer', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (208, 'schooling', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (209, 'disguise', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (210, 'battle-bond', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (211, 'power-construct', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (212, 'corrosion', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (213, 'comatose', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (214, 'queenly-majesty', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (215, 'innards-out', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (216, 'dancer', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (217, 'battery', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (218, 'fluffy', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (219, 'dazzling', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (220, 'soul-heart', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (221, 'tangling-hair', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (222, 'receiver', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (223, 'power-of-alchemy', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (224, 'beast-boost', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (225, 'rks-system', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (226, 'electric-surge', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (227, 'psychic-surge', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (228, 'misty-surge', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (229, 'grassy-surge', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (230, 'full-metal-body', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (231, 'shadow-shield', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (232, 'prism-armor', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (233, 'neuroforce', 7);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (165, 'aroma-veil', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (166, 'flower-veil', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (167, 'cheek-pouch', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (168, 'protean', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (169, 'fur-coat', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (170, 'magician', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (171, 'bulletproof', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (172, 'competitive', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (173, 'strong-jaw', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (174, 'refrigerate', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (175, 'sweet-veil', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (176, 'stance-change', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (177, 'gale-wings', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (178, 'mega-launcher', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (179, 'grass-pelt', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (180, 'symbiosis', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (181, 'tough-claws', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (182, 'pixilate', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (183, 'gooey', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (184, 'aerilate', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (185, 'parental-bond', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (186, 'dark-aura', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (187, 'fairy-aura', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (188, 'aura-break', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (189, 'primordial-sea', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (190, 'desolate-land', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (191, 'delta-stream', 6);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (124, 'pickpocket', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (125, 'sheer-force', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (126, 'contrary', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (127, 'unnerve', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (128, 'defiant', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (129, 'defeatist', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (130, 'cursed-body', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (131, 'healer', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (132, 'friend-guard', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (133, 'weak-armor', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (134, 'heavy-metal', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (135, 'light-metal', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (136, 'multiscale', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (137, 'toxic-boost', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (138, 'flare-boost', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (139, 'harvest', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (140, 'telepathy', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (141, 'moody', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (142, 'overcoat', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (143, 'poison-touch', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (144, 'regenerator', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (145, 'big-pecks', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (146, 'sand-rush', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (147, 'wonder-skin', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (148, 'analytic', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (149, 'illusion', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (150, 'imposter', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (151, 'infiltrator', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (152, 'mummy', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (153, 'moxie', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (154, 'justified', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (155, 'rattled', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (156, 'magic-bounce', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (157, 'sap-sipper', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (158, 'prankster', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (159, 'sand-force', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (160, 'iron-barbs', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (161, 'zen-mode', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (162, 'victory-star', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (163, 'turboblaze', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (164, 'teravolt', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10001, 'mountaineer', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10002, 'wave-rider', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10003, 'skater', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10004, 'thrust', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10005, 'perception', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10006, 'parry', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10007, 'instinct', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10008, 'dodge', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10009, 'jagged-edge', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10010, 'frostbite', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10011, 'tenacity', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10012, 'pride', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10013, 'deep-sleep', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10014, 'power-nap', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10015, 'spirit', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10016, 'warm-blanket', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10017, 'gulp', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10018, 'herbivore', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10019, 'sandpit', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10020, 'hot-blooded', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10021, 'medic', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10022, 'life-force', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10023, 'lunchbox', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10024, 'nurse', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10025, 'melee', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10026, 'sponge', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10027, 'bodyguard', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10028, 'hero', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10029, 'last-bastion', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10030, 'stealth', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10031, 'vanguard', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10032, 'nomad', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10033, 'sequence', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10034, 'grass-cloak', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10035, 'celebrate', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10036, 'lullaby', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10037, 'calming', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10038, 'daze', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10039, 'frighten', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10040, 'interference', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10041, 'mood-maker', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10042, 'confidence', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10043, 'fortune', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10044, 'bonanza', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10045, 'explode', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10046, 'omnipotent', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10047, 'share', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10048, 'black-hole', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10049, 'shadow-dash', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10050, 'sprint', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10051, 'disgust', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10052, 'high-rise', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10053, 'climber', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10054, 'flame-boost', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10055, 'aqua-boost', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10056, 'run-up', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10057, 'conqueror', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10058, 'shackle', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10059, 'decoy', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10060, 'shield', 5);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (77, 'tangled-feet', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (78, 'motor-drive', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (79, 'rivalry', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (80, 'steadfast', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (81, 'snow-cloak', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (82, 'gluttony', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (83, 'anger-point', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (84, 'unburden', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (85, 'heatproof', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (86, 'simple', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (87, 'dry-skin', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (88, 'download', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (89, 'iron-fist', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (90, 'poison-heal', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (91, 'adaptability', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (92, 'skill-link', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (93, 'hydration', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (94, 'solar-power', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (95, 'quick-feet', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (96, 'normalize', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (97, 'sniper', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (98, 'magic-guard', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (99, 'no-guard', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (100, 'stall', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (101, 'technician', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (102, 'leaf-guard', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (103, 'klutz', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (104, 'mold-breaker', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (105, 'super-luck', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (106, 'aftermath', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (107, 'anticipation', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (108, 'forewarn', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (109, 'unaware', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (110, 'tinted-lens', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (111, 'filter', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (112, 'slow-start', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (113, 'scrappy', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (114, 'storm-drain', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (115, 'ice-body', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (116, 'solid-rock', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (117, 'snow-warning', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (118, 'honey-gather', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (119, 'frisk', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (120, 'reckless', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (121, 'multitype', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (122, 'flower-gift', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (123, 'bad-dreams', 4);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (1, 'stench', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (2, 'drizzle', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (3, 'speed-boost', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (4, 'battle-armor', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (5, 'sturdy', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (6, 'damp', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (7, 'limber', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (8, 'sand-veil', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (9, 'static', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (10, 'volt-absorb', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (11, 'water-absorb', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (12, 'oblivious', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (13, 'cloud-nine', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (14, 'compound-eyes', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (15, 'insomnia', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (16, 'color-change', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (17, 'immunity', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (18, 'flash-fire', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (19, 'shield-dust', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (20, 'own-tempo', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (21, 'suction-cups', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (22, 'intimidate', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (23, 'shadow-tag', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (24, 'rough-skin', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (25, 'wonder-guard', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (26, 'levitate', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (27, 'effect-spore', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (28, 'synchronize', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (29, 'clear-body', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (30, 'natural-cure', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (31, 'lightning-rod', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (32, 'serene-grace', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (33, 'swift-swim', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (34, 'chlorophyll', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (35, 'illuminate', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (36, 'trace', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (37, 'huge-power', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (38, 'poison-point', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (39, 'inner-focus', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (40, 'magma-armor', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (41, 'water-veil', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (42, 'magnet-pull', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (43, 'soundproof', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (44, 'rain-dish', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (45, 'sand-stream', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (46, 'pressure', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (47, 'thick-fat', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (48, 'early-bird', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (49, 'flame-body', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (50, 'run-away', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (51, 'keen-eye', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (52, 'hyper-cutter', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (53, 'pickup', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (54, 'truant', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (55, 'hustle', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (56, 'cute-charm', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (57, 'plus', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (58, 'minus', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (59, 'forecast', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (60, 'sticky-hold', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (61, 'shed-skin', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (62, 'guts', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (63, 'marvel-scale', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (64, 'liquid-ooze', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (65, 'overgrow', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (66, 'blaze', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (67, 'torrent', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (68, 'swarm', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (69, 'rock-head', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (70, 'drought', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (71, 'arena-trap', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (72, 'vital-spirit', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (73, 'white-smoke', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (74, 'pure-power', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (75, 'shell-armor', 3);

INSERT INTO ABILITY (ID_ABILITY, NAME_A, REGION) 
VALUES (76, 'air-lock', 3);

