INSERT INTO REGION (ID_REGION, NAME_R) 
VALUES (1, 'kanto');

INSERT INTO REGION (ID_REGION, NAME_R) 
VALUES (2, 'johto');

INSERT INTO REGION (ID_REGION, NAME_R) 
VALUES (3, 'hoenn');

INSERT INTO REGION (ID_REGION, NAME_R) 
VALUES (4, 'sinnoh');

INSERT INTO REGION (ID_REGION, NAME_R) 
VALUES (5, 'unova');

INSERT INTO REGION (ID_REGION, NAME_R) 
VALUES (6, 'kalos');

INSERT INTO REGION (ID_REGION, NAME_R) 
VALUES (7, 'alola');

INSERT INTO REGION (ID_REGION, NAME_R) 
VALUES (8, 'galar');

