INSERT INTO DAMAGE_CLASS (ID_DAMAGE_CLASS, NAME_DAMAGE_CLASS) 
VALUES (1, 'status');

INSERT INTO DAMAGE_CLASS (ID_DAMAGE_CLASS, NAME_DAMAGE_CLASS) 
VALUES (2, 'physical');

INSERT INTO DAMAGE_CLASS (ID_DAMAGE_CLASS, NAME_DAMAGE_CLASS) 
VALUES (3, 'special');
