INSERT INTO MOVE_METHOD (ID_MOVE_METHOD, NAME_MOVE_METHOD) 
VALUES (1, 'level-up');

INSERT INTO MOVE_METHOD (ID_MOVE_METHOD, NAME_MOVE_METHOD) 
VALUES (2, 'egg');

INSERT INTO MOVE_METHOD (ID_MOVE_METHOD, NAME_MOVE_METHOD) 
VALUES (3, 'tutor');

INSERT INTO MOVE_METHOD (ID_MOVE_METHOD, NAME_MOVE_METHOD) 
VALUES (4, 'machine');

INSERT INTO MOVE_METHOD (ID_MOVE_METHOD, NAME_MOVE_METHOD) 
VALUES (5, 'stadium-surfing-pikachu');

INSERT INTO MOVE_METHOD (ID_MOVE_METHOD, NAME_MOVE_METHOD) 
VALUES (6, 'light-ball-egg');

INSERT INTO MOVE_METHOD (ID_MOVE_METHOD, NAME_MOVE_METHOD) 
VALUES (7, 'colosseum-purification');

INSERT INTO MOVE_METHOD (ID_MOVE_METHOD, NAME_MOVE_METHOD) 
VALUES (8, 'xd-shadow');

INSERT INTO MOVE_METHOD (ID_MOVE_METHOD, NAME_MOVE_METHOD) 
VALUES (9, 'xd-purification');

INSERT INTO MOVE_METHOD (ID_MOVE_METHOD, NAME_MOVE_METHOD) 
VALUES (10, 'form-change');

INSERT INTO MOVE_METHOD (ID_MOVE_METHOD, NAME_MOVE_METHOD) 
VALUES (11, 'zygarde-cube');

